name: test

on:
  schedule:
     - cron: '0 3,20 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.getversion.outputs.tag }}
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: Get version
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r '.tag_name'`
          tag=`curl https://api.github.com/repos/tailscale/tailscale/releases/latest | jq -r '.tag_name' | tr -d 'v'`
          cver=`curl https://api.github.com/repos/lmq8267/tailscale/releases/latest | jq -r '.tag_name'`
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      - 
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build
        run: |
          git clone https://github.com/tailscale/tailscale ../src
          git clone https://github.com/lmq8267/cloudflared.git /opt/st
          cd ../src
          sed -i 's|return strings.TrimSpace(tailscaleroot.VersionDotTxt) + "-ERR-BuildInfo"|return strings.TrimSpace(tailscaleroot.VersionDotTxt)|g' ./version/version.go
          sed -i 's|return fmt.Sprintf("%s-dev%s-t%s%s", strings.TrimSpace(tailscaleroot.VersionDotTxt), bi.commitDate, bi.commitAbbrev(), dirtyString())|return fmt.Sprintf(strings.TrimSpace(tailscaleroot.VersionDotTxt))|g' ./version/version.go
          sed -i 's|return strings.TrimSpace(tailscaleroot.VersionDotTxt) + "-dev" + bi.commitDate|return strings.TrimSpace(tailscaleroot.VersionDotTxt)|g' ./version/version.go
          sed -i 's|return "/var/lib/tailscale/tailscaled.state"|return "/etc/storage/tailscale/lib/tailscaled.state"|g' ./paths/paths_unix.go
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/st/strip
          sudo apt-get update && sudo apt-get install vite
          export QT_DEBUG_PLUGINS=1 
          sudo apt-get install xvfb
          pip install pyvirtualdisplay
          sudo apt-get install libgl1-mesa-dev
          sudo apt-get install python-opengl
          ./tool/yarn --cwd client/web build
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build tailscale.com/cmd/tailscale
          CGO_ENABLED=0 GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build tailscale.com/cmd/tailscaled
          /opt/st/strip tailscale
          /opt/st/strip tailscaled
          /opt/upx-3.95-amd64_linux/upx --lzma --best tailscale
          /opt/upx-3.95-amd64_linux/upx --lzma --best tailscaled
          echo $(md5sum tailscale | awk '{print $1;}') >tailscale.txt
          echo $(md5sum tailscaled | awk '{print $1;}') >tailscaled.txt
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.c8 }}
          tag_name: test
          files: |
              ../src/tailscale
              ../src/tailscale.txt
              ../src/tailscaled
              ../src/tailscaled.txt
     
