name: 删除工作流
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'
    
jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
    
    - name: 删除工作流
      uses: GitRML/delete-workflow-runs@main
      with:
        token: ${{ secrets.c8 }}
        retain_days: 2
        keep_minimum_runs: 0
